Andy info
HYF-Class20/home pull request #100
Opened 2023-04-10 18:44 UTC by andykeshishian

## Checklists

### General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work
- [ ] any embedded code snippets are formatted

2023-04-10 20:23 UTC, talmurshidi commented
Please create an issue with check list and link it to this PR

2023-04-10 20:56 UTC, bermarte commented on student-bios/andy-keshishian.md
> +## **languages that is can speak**
Better 'languages that I can speak', for the rest is ok. Don't forget to make an issue and link it to your PR.

2023-04-10 20:56 UTC, bermarte requested changes
Follow Tamer's indications than you are good to go!

2023-04-12 13:45 UTC, bermarte approved these changes

2023-04-12 13:46 UTC, merged