my info and picture
HYF-Class20/home pull request #7
Opened 2023-03-21 17:10 UTC by emran-ai

## Checklists

### General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work
- [x] any embedded code snippets are formatted

2023-03-21 18:50 UTC, bermarte requested changes
Be sure to pass the CI check, then we will merge it.

2023-03-22 10:22 UTC, talmurshidi commented
Please create a `images` folder inside `student-bios` folder then you can add your photo inside images folder and delete it from assets folder.
Please make sure to update your branch using `git pull origin main` every time before pushing your changes.

2023-03-22 13:23 UTC, bermarte requested changes
Hi, you should not change the README file, be sure you add one file at a time to avoid this error.

2023-03-22 13:27 UTC, bermarte commented on student-bios/emran-ai.md
> +Hi, everyone! My name is Emran and I'm a student. I'm excited to be part of this
I am a bit confused about this commit, the message says 
> add item to .c spell.json
but you just changed the link to your image (line 16)

2023-03-22 13:32 UTC, bermarte commented on README.md
>  <!-- BEGIN TOP -->
You should restore the original README, have a look to [the documentation](https://stackoverflow.com/questions/307579/how-do-i-copy-a-version-of-a-single-file-from-one-git-branch-to-another)

2023-03-22 13:33 UTC, bermarte requested changes
https://stackoverflow.com/questions/307579/how-do-i-copy-a-version-of-a-single-file-from-one-git-branch-to-another

2023-03-22 14:19 UTC, bermarte requested changes
Please restore the previous README.

2023-03-23 15:35 UTC, merged